name: Deploy Chambita Web

on:
  push:
    branches:
      - main # Se activa solo en pushes a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: chambitaweb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Compress build output
        run: zip -r out.zip ./out/

      - name: Deploy and extract to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: ./out.zip
          remote_path: ${{ secrets.FTP_REMOTE_DIR }}
          sftp_only: true
          post_upload_commands: |
            cd ${{ secrets.FTP_REMOTE_DIR }}
            unzip -o out.zip
            mv out/* .
            rmdir out
            rm out.zip
